# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [1]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [83]:
A = np.arange(1, 16).reshape(3,5)
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [165]:
print(f"Nr of Axes: {np.ndim(A)}")
print(f"Shape: {np.shape(A)}")
print(f"Size: {np.size(A)}")
print(f"Datatype: {type(A)}")

Nr of Axes: 2
Shape: (2, 2)
Size: 4
Datatype: <class 'numpy.ndarray'>


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [170]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [171]:
print(f"B - C:\n{B-C}")
print()
print(f"B * C:\n{B*C}")
print()
print(f"B @ C:\n{B@C}")

B - C:
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

B * C:
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

B @ C:
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [20]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [183]:
print(f"Exponatiate each number:\n {np.exp(B)}")
print()
print(f"Min-value matrix: {np.min(B)}")
print(f"Min-value each row: {np.min(B, axis=1)}")
print(f"Min-value each column: {np.min(B, axis=0)}")
print(f"Index-value for min-value matrix: {np.argmin(B)}")
print(f"Index-value for min-value each row: {np.argmin(B, axis=1)}")
print(f"Sum of all elements: {np.sum(B)}")
print(f"Mean of all elements: {np.mean(B)}")
print(f"Median of all elements: {np.median(B)}")

Exponatiate each number:
 [[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

Min-value matrix: 1
Min-value each row: [1 4 7]
Min-value each column: [1 2 3]
Index-value for min-value matrix: 0
Index-value for min-value each row: [0 0 0]
Sum of all elements: 45
Mean of all elements: 5.0
Median of all elements: 5.0


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [40]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [41]:
A[1]

array([ 6,  7,  8,  9, 10])

In [42]:
A[1, :]

array([ 6,  7,  8,  9, 10])

In [43]:
A[1, ]

array([ 6,  7,  8,  9, 10])

**Answer:**

If fewer indicies than axes are provided, the missing indices are considered complete slices :.

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [44]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [45]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [48]:
for i in A:
    for j in i:
        print(j)
        
# Works good for two dimensions, but will be very tedious for multiple dimensions. Use nditer() as shown in next codeblock preferably. 

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [49]:
for i in np.nditer(A):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [50]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


1: Creates a 1-dimensional array a with number 0-29. 
2: Creates a 3-dimensional (3 axes) array by reshaping array a. The array consist of 2 blocks, with 3 rows each. The -1 means the python will create as many columns as necessary to complete the array. 
3: a och b are printed. Note the the .reshape()-function returns a modified array, which we store in b, but will not change the original array a!

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [51]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [52]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [53]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [249]:
def add_mult_matrices(arr1, arr2, operator):
    isArray = isinstance(arr1, np.ndarray) and isinstance(arr2, np.ndarray)
    isOperator = operator == "add" or operator == "multiply"
    
    if isArray and isOperator:
        if operator == "add":
            if np.shape(arr1) == np.shape(arr2):
                return arr1 + arr2
            else:
                print("When doing matrix addition, the two matrices needs to have the same dimensions.")
        elif operator == "multiply":
            if arr1.ndim == 1:
                arr1 = arr1.reshape(1, -1)
            if arr2.ndim == 1: 
                arr2 = arr2.reshape(1, -1)
            
            if arr1.shape[1] == arr2.shape[0]: 
                return arr1 @ arr2
            else: 
                print("When doing matrix multiplication, the first matrix needs to have as many columns as the second matrix have rows.")
    else:
        print("You must give two numpy arrays and 'add' or 'multiply' as arguments.") 
        
        
            
arr1 = np.array([1, 2, 3])
arr2 = np.array([[4, 5, 6,], [7, 8, 9], [10, 11, 12]])

add_mult_matrices(arr1, arr2, "multiply")

array([[48, 54, 60]])

### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [241]:
## 10.1.1
print("10.1.1")

x = np.array([4, 3])

# a 
x_reshape = x.reshape(1, -1) # HUR HANTERA DETTA ????? 
print(f"a: {np.shape(x_reshape)}")

# b
print(f"b: {5 * x}")

# c
print(f"c: {3 * x}")

# d
print(f"d: {5*x - 3*x}")

# e
print(f"e: {8 * x}")

# f
print(f"f: {4*x - x}")

# g
# np.transpose(x) has no effect because it is not a matrix/has only 1 D
x_transpose = x.reshape(-1, 1)
print(f"g:\n {x_transpose}, {np.shape(x_transpose)}")

# h Not defined due to different shapes.
print("h: Not defined") 

# i
print(f"i: {np.linalg.norm(x)}")

print("\n")
## 10.1.2
print("10.1.2")

v = np.array([3, 7, 0, 11]).reshape(-1, 1)

# a 
print(f"a: {np.shape(v)}")

# b 
print(f"b:\n {2 * v}")

# c
print(f"c:\n {5*v + 2*v}")

# d
print(f"d:\n {4*v - 2*v}")

# e
v_transpose = np.transpose(v)
print(f"e:\n {v_transpose}, {np.shape(v_transpose)}")

# f
print(f"f: {np.linalg.norm(v)}")

print("\n")
## 10.1.3 
print("10.1.3")

v1 = np.array([4, 3, 1, 5])
v2 = np.array([2, 3, 1, 1])

# a 
print(f"a: {np.linalg.norm(v1)}")

# b
print(f"b: {np.linalg.norm(v1-v2)}")

10.1.1
a: (1, 2)
b: [20 15]
c: [12  9]
d: [8 6]
e: [32 24]
f: [12  9]
g:
 [[4]
 [3]], (2, 1)
h: Not defined
i: 5.0


10.1.2
a: (4, 1)
b:
 [[ 6]
 [14]
 [ 0]
 [22]]
c:
 [[21]
 [49]
 [ 0]
 [77]]
d:
 [[ 6]
 [14]
 [ 0]
 [22]]
e:
 [[ 3  7  0 11]], (1, 4)
f: 13.379088160259652


10.1.3
a: 7.14142842854285
b: 4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [239]:
## 10.2.1
print("10.2.1")

A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])
C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])
E = np.array([[1], [2]])
I = np.array([[1, 0], [0, 1]])

# a 
print(f"a:\n {2 * A}")

# b 
print(f"b:\n {B -2*A}")

# c Not defined
print("c: Not defined")

# d 
print(f"d:\n {2*D - 3*C}")

# e 
print(f"e:\n {D.T - 2*D}")

# f 
print(f"f:\n {2*C.T - 2*D.T}")

# g Not defined
print("g: Not defined") 

# h Not defined
print("h: Not defined")

# i 
print(f"i:\n {C @ D}")

# j
print(f"j:\n {C @ B}")

# k
print(f"k:\n {C @ I}")

# l
print(f"l:\n {A @ B.T}")

print("\n")
## 10.2.2
print("10.2.2")

A = np.array([[2, 3, 4], [5, 4, 1]])

print(A @ A.T)

print("\n")
## 10.2.3
print("10.2.3")

A = np.array([[1, 2], [2, 4]])
B = np.array([[2, 1], [1, 3]])
C = np.array([[4, 3], [0, 2]])

print(np.array_equal(A @ B, A @ C))

10.2.1
a:
 [[ 4  2 -2]
 [ 2 -2  2]]
b:
 [[ 0 -4  3]
 [ 0 -2 -4]]
c: Not defined
d:
 [[3 2]
 [2 3]]
e:
 [[-3 -4]
 [-4 -3]]
f:
 [[-4 -4]
 [-4 -4]]
g: Not defined
h: Not defined
i:
 [[11 10]
 [10 11]]
j:
 [[  8 -10  -3]
 [ 10  -8   0]]
k:
 [[1 2]
 [2 1]]
l:
 [[5 2]
 [7 4]]


10.2.2
[[29 26]
 [26 42]]


10.2.3
True


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [160]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [158]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[  0   1   2 123]


In [159]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
